SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        //Cart object is now supplied by model binder
        //public Cart GetCart()
        //{
        //    Cart cart = Session["Cart"] as Cart;
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.Where(p => p.ProductID == productId).FirstOrDefault();
            if (product != null)
            {
                cart.AddItem(product, 1, 0);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.Where(p => p.ProductID == productId).FirstOrDefault();
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult DeleteAddress(string returnURL, int CustomerAddressID = 0)
        {
            if (CustomerAddressID != 0)
            {
                repository.DeleteCustomerAddress(CustomerAddressID);
                return RedirectToAction("Checkout", new { returnURL });
            }
            else
            {
                return RedirectToRoute(new { controller = "Product", action = "Index" });
            }
        }
        [HttpGet]
        public ActionResult CreateEditAddress(int CustomerAddressID = 0)
        {
            var lstOfCountries = repository.Countries.ToList<Country>();
            List<SelectListItem> selectCountryList = new List<SelectListItem>();
            foreach (var item in lstOfCountries)
            {
                if (item.States.Count > 0)
                {
                    selectCountryList.Add(new SelectListItem { Text = item.CountryName, Value = item.CountryID.ToString() });
                }
            }
            ViewData["Countries"] = selectCountryList;
            if (CustomerAddressID != 0)
            {
                CustomerAddress customerAddress = repository.CustomerAddresses.FirstOrDefault(p => p.CustomerAddressID == CustomerAddressID);
                selectCountryList.FirstOrDefault(p => p.Value == customerAddress.CountryID.ToString()).Selected = true;
                return View("Address", customerAddress);
            }
            else
            {
                return View("Address", new CustomerAddress { CustomerID = Convert.ToInt32(User.Identity.GetUserId()) });
            }
        }
        [HttpPost]
        public RedirectToRouteResult CreateEditAddress(CustomerAddress customerAddress, string returnURL)
        {
            if (ModelState.IsValid && customerAddress != null)
            {
                repository.SaveCustomerAddress(customerAddress);
            }
            return RedirectToAction("Checkout", new { returnURL });
        }
        public RedirectToRouteResult UpdateCart(Cart cart, string returnUrl, List<ProductCartList> lstProductCartList)
        {
            if (lstProductCartList != null || lstProductCartList.Count != 0)
            {
                foreach (var item in lstProductCartList)
                {
                    Product product = repository.Products.Where(p => p.ProductID == item.ProductID).FirstOrDefault();
                    if (product != null)
                    {
                        cart.AddItem(product, item.Quantity, 1);
                    }
                }
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        [HttpGet]
        public ViewResult Checkout()
        {

            return View(new CheckOutViewModel());
        }
        //[HttpPost]
        //public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        //{
        //    if (cart.Lines.Count() == 0)
        //    {
        //        ModelState.AddModelError("", "Sorry your cart is empty!");
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        orderProcessor.ProcessOrder(cart, shippingDetails);
        //        cart.Clear();
        //        return View("Completed");
        //    }
        //    else
        //    {
        //        return View(shippingDetails);
        //    }
        //}
        public PartialViewResult AuthenticatedAddressCheckoutForm(int CustomerID = 0)
        {
            if (CustomerID != 0)
            {
                var lstOfCountries = repository.Countries.ToList<Country>();
                List<SelectListItem> selectCountryList = new List<SelectListItem>();
                foreach (var item in lstOfCountries)
                {
                    if (item.States.Count > 0)
                    {
                        selectCountryList.Add(new SelectListItem { Text = item.CountryName, Value = item.CountryID.ToString() });
                    }
                }
                ViewData["Countries"] = selectCountryList;
                var allCustomerAddresses = repository.CustomerAddresses.Where(p => p.CustomerID == CustomerID).ToList<CustomerAddress>();
                ViewData["CustomerID"] = User.Identity.GetUserId();
                if (allCustomerAddresses.Count > 0)
                {
                    return PartialView("Partial/_AuthenticatedCheckoutForm", allCustomerAddresses);
                }
                else
                {
                    return PartialView("Partial/_AuthenticatedCustomerAddressFillForm", allCustomerAddresses);
                }
            }
            else
            {
                return null;
            }
        }

        [HttpPost]
        public ActionResult AuthenticatedCheckout(Cart cart, CustomerAddress BillingAddress, CustomerAddress ShippingAddress, bool? IsShippingAddressChecked)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                if (User.Identity.IsAuthenticated)
                {
                    //Below condition handles first time checkout or no addresses in the database 
                    //for a registered user
                    if (BillingAddress.CustomerAddressID == 0)
                    {
                        BillingAddress.IsBillingAddress = true;
                        BillingAddress.IsShippingAddress = true;
                        repository.SaveCustomerAddress(BillingAddress);
                        //Code to save billing address in order address table with 
                        //billing address = 1 and shipping address = 0
                        if (IsShippingAddressChecked == true)
                        {
                            ShippingAddress.IsBillingAddress = false;
                            ShippingAddress.IsShippingAddress = true;
                            repository.SaveCustomerAddress(ShippingAddress);
                            //Need to save this address in order address table with isbilling and isshipping equal to 1
                            //save billingaddress in order address with isshipping = false
                            //save shipping address in order address with ishipping = true
                        }
                        else
                        {
                            //save billing address in order address with isbilling = true
                            //and ishipping = true
                        }
                    }
                    //The below condition needs to handle the pre saved addresses of a
                    //registered customer
                    else
                    {
                        //Decide whether the BillingAddress and Shipping Address are same or not
                        if(BillingAddress.CustomerAddressID == ShippingAddress.CustomerAddressID)
                        {
                            //Save a Billing Address in order address with ishipping = isbilling = true
                        }
                        else
                        {
                            //Save two addresses in order address with billing address = 1,ishipping = 0 and isbilling = 0,ishipping = 1 for other one
                        }
                        
                        //get the customeraddress id of the selected addresses
                        //get the list of all addresses from the database
                        //if the selected address by the customer is billing address
                        //then store the billing address in order addres with isshipping = true
                        //isbilling = true or else save the billing address with isbilling = true
                        //isshipping = false and save the selected address by the customer with

SportsStore.WebUI/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string CategoryName = null)
        {
            ViewBag.SelectedCategory = CategoryName;
            var tempCategoryViewModel = from pc in repository.ProductCategories
                                        join c in repository.Categories
                                        on
                                        pc.CategoryID equals c.CategoryID
                                        group c by new { c.CategoryID, c.Name } into result
                                        select new ProductCategoryViewModel
                                        {
                                            CategoryID = result.First().CategoryID,
                                            CategoryName = result.First().Name,
                                            ProductNos = result.Count()
                                        };
            List<ProductCategoryViewModel> lstOfProdCatViewModel = new List<ProductCategoryViewModel>();
            foreach (var item in tempCategoryViewModel)
            {
                lstOfProdCatViewModel.Add((ProductCategoryViewModel)item);
            }

            Dictionary<string, int> nameAndCount = new Dictionary<string, int>();


            ViewBag.TotalCount = lstOfProdCatViewModel.Sum(x => x.ProductNos);
            return PartialView("HorizontalMenu", lstOfProdCatViewModel);
        }
    }
}

SportsStore.WebUI/Views/Shared/ProductSummary.Mobile.cshtml
@model SportsStore.Domain.Entities.Product
<div data-role="collapsible" data-collapsed="false" data-contenttheme="c">
    <h2>
        @Model.Name
    </h2>
    <div class="ui-grid-b">
        <div class="ui-block-a">
            @Model.Description
        </div>
        <div class="ui-block-b">
            <strong>(@Model.Price.ToString("c"))</strong>
        </div>
        <div class="ui-block-c">
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.ProductID)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" data-inline="true"
                       data-mini="true" value="Add to cart" />
            }
        </div>
    </div>
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.WebUI.Models.ProductImageViewModel

<div class="col-sm-3 col-md-3 thumbnail btn-sharp" style="margin: 5px">
    <div>
        <img src="@Model.ImagePath" width="100%" height="200px" alt="..." />
        <div class="caption">
            <div style="font-size:medium;font-weight:bold" class="clampString">@Model.Name</div>
            <div class="clampString">@Model.ShortDescription</div>
            <span style="text-align: center">
                <span style="font-size:medium;font-weight:bold">@Model.AltPrice.ToString("c")</span>
            </span>
        </div>
        <a href='@Url.Action("ProductView", new { controller = "QuickView", ProductID = @Model.ProductID })' class="btn btn-quickview pull-left btn-sharp">Quick View</a>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.Hidden("ProductID", Model.ProductID)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-sharp btn-addtocart" value="Add to cart" />
            </div>
        }
    </div>
</div>

SportsStore.WebUI/Views/Shared/_ExternalLoginsListPartial.cshtml
@model SportsStore.WebUI.Models.ExternalLoginListViewModel
@using Microsoft.Owin.Security

<h4>Use another service to log in.</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {
        <div>
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=403804">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else {
        using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = Model.ReturnUrl })) {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in loginProviders) {
                        <button type="submit" class="btn btn-blue btn-sharp text-uppercase" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                    }
                </p>
            </div>
        }
    }
}

SportsStore.WebUI/Views/Shared/_FooterGeneralContent.cshtml
<div class="col-md-12 footer-container-content">
    <div class="col-md-3">
        <p><i class="fa fa-futbol-o fa-2x"></i> <span class="h3" style="padding-left:10px"> Shopping Store</span></p>
        <p style="font-size:0.9em">
            Nulla facilisis feugiat magna, ut molestie metus hendrerit vitae. Vivamus tristique lectus at varius rutrum. Integer lobortis mauris non consectetur eleifend.
        </p>
    </div>
    <div class="col-md-6">
        <div class="col-md-2" style="width:33%">
            <span class="h4">CUSTOMER SERVICE</span>
            <ul style="margin-top:10px" class="fa-ul">
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Order Status</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Payment Methods</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Delivery & Returns</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Privacy Policy</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Terms & Conditions</a></li>
            </ul>
        </div>
        <div class="col-md-2" style="width:33%">
            <span class="h4">MY ACCOUNT</span>
            <ul style="margin-top:10px" class="fa-ul">
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">My Account</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Order History</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Wishlist</a></li>

            </ul>
        </div>
        <div class="col-md-2" style="width:33%">
            <span class="h4">MISCALLANEOUS</span>
            <ul style="margin-top:10px" class="fa-ul">
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Online Shopping</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Affiliate</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">e-gift-voucher</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">Online Cancellations</a></li>
                <li><i class="fa-li fa fa-angle-right"></i><a href="#">FAQ</a></li>
            </ul>
        </div>
    </div>
    <div class="col-md-3">
        <p><i class="fa fa-newspaper-o fa-2x"></i> <span class="h3" style="padding-left:10px">NEWSLETTER</span></p>
        <p>Sign up to receive email updates on new product announcements, gift ideas, special promotions, sales and more.</p>
        <div class="col-md-12" style="padding:0px"><div class="col-md-8" style="padding:0px"><input type="text" placeholder="mail@example.com" class="form-control btn-sharp" /></div><div class="col-md-4" style="padding:0px"><button class="btn btn-sharp" style="background-color:#b71c1c;color:white">JOIN</button></div></div>
    </div>

</div>
<div class="col-md-12" style="background-color:#042981;padding-top:10px;padding-bottom:10px">
    <div class="col-md-12 text-center">
        <span style="padding-right:5px"><i class="fa fa-cc-paypal fa-2x"></i></span>
        <span style="padding-right:5px"><i class="fa fa-google-paypal fa-2x"></i></span>
        <span style="padding-right:5px"><i class="fa fa-credit-card fa-2x"></i></span>
        <span style="padding-right:5px"><i class="fa fa-cc-visa fa-2x"></i></span>
        <span style="padding-right:5px"><i class="fa fa-cc-amex fa-2x"></i></span>
        <span style="padding:5px;" class="h2">Cash on Delivery</span>
    </div>
</div>

SportsStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/jquery.mobile-1.4.2.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/jquery.mobile-1.4.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>SportsStore</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.dotdotdot.min.js"></script>
    <script src="~/Scripts/jquery.jcarousellite.js"></script>
    <script src="~/Scripts/jquery.easing.1.3.js"></script>
    <script src="~/Scripts/CustomScripts.js"></script>

    <title>@ViewBag.Title</title>
</head>
<body>
    <div id="navbar-container" class="navbar navbar-custom navbar-fixed-top no-padding" role="navigation">
        <div id="navbar-brand-container" class="col-md-6">
            <a class="navbar-brand" href="#">
                <span style="font-family:'Comic Sans MS';font-size:25px">SHOPPING STORE</span>
            </a>
        </div>
        <div id="navbar-user-info" class="col-md-6">
            @Html.Partial("_LoginPartial")
            @Html.Action("Summary", "Cart")
            <form role="search" class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" placeholder="Search" class="form-control btn-sharp">
                    <button type="submit" class="btn btn-green btn-sharp"><span class="glyphicon glyphicon-search"></span></button>
                </div>
            </form>
        </div>
    </div>
    <div style="max-width: 1000px" class="navbar center-block" role="navigation">
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav nav-tabs nav-pills nav-justified">
                @Html.Action("Menu", "Nav")
            </ul>
        </div>
    </div>
    <div class="container" id="CenteredContent">
        <div>
            @RenderBody()
        </div>
    </div>
    <footer class="footer footer-color" style="padding-bottom:0px;padding-right:0px;padding-left:0px">
        <div class="container footer-container">
            @Html.Partial("_FooterGeneralContent")
        </div>
    </footer>
</body>
</html>