SportsStore.WebUI.Admin/Controllers/ProductAdminController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Admin.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Admin.Controllers
{
    public class ProductAdminController : Controller
    {
        private IProductRepository repository;
        public ProductAdminController(IProductRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Products);
        }
        [HttpGet]
        public ActionResult Edit(int productId)
        {
            if (productId != 0)
            {
                Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
                return View(product);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }
        public ViewResult Create()
        {
            return View("Edit", new Product());
        }
        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deletedProduct = repository.DeleteProduct(productId);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted ", deletedProduct.Name);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UploadImage(int ProductID = 0)
        {
            if (ProductID == 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                Image image = repository.Images.FirstOrDefault(p => p.ProductID == ProductID);
                if (image != null)
                {
                    ViewBag.ProductName = image.Product.Name;
                }
                else
                {
                    ViewBag.ProductName = "New Product";
                }
            
                return View("UploadImage", new ImageUploadViewModel());
            }
        }
        [HttpPost]
        public ActionResult UploadImage(ImageUploadViewModel imageUploadViewModel)
        {
            if (ModelState.IsValid && imageUploadViewModel != null)
            {
                Image image = repository.Images.FirstOrDefault(p => p.ProductID == imageUploadViewModel.ProductID);
                if(image == null)
                {
                    image = new Image();
                }
                string applicationPath = ConfigurationManager.AppSettings["ImagePath"].ToString();
                //Storing image description
                image.ImageDescription = imageUploadViewModel.ImageDescription;

                //Storing Small Image Path
                if (imageUploadViewModel.SmallImage != null)
                {
                    string smallImageFileName = Guid.NewGuid().ToString() + Path.GetFileName(imageUploadViewModel.SmallImage.FileName);
                    string smallImageFilePath = Path.Combine(Server.MapPath(applicationPath), smallImageFileName);
                    image.SmallImage = string.Format(@"http://localhost:49217/Content/images/cart-image-icons/{0}", smallImageFileName);
                    imageUploadViewModel.SmallImage.SaveAs(smallImageFilePath);
                }
                else
                {
                    image.SmallImage = null;
                }


                //Storing Medium Image Path
                if (imageUploadViewModel.MediumImage != null)
                {
                    string mediumImageFileName = Guid.NewGuid().ToString() + Path.GetFileName(imageUploadViewModel.MediumImage.FileName);
                    string mediumImageFilePath = Path.Combine(Server.MapPath(applicationPath), mediumImageFileName);
                    //Temporary Adjustment for image path storing
                    //Change the below URL for respective environment
                    image.MediumImage = string.Format(@"http://localhost:49217/Content/images/cart-image-icons/{0}", mediumImageFileName);
                    //image.MediumImage = mediumImageFilePath;
                    imageUploadViewModel.MediumImage.SaveAs(mediumImageFilePath);
                }
                else
                {
                    image.MediumImage = null;
                }

                //Storing Large Image Path
                if (imageUploadViewModel.LargeImage != null)
                {
                    string largeImageFileName = Guid.NewGuid().ToString() + Path.GetFileName(imageUploadViewModel.LargeImage.FileName);
                    string largeImageFilePath = Path.Combine(Server.MapPath(applicationPath), largeImageFileName);
                    image.LargeImage = string.Format(@"http://localhost:49217/Content/images/cart-image-icons/{0}",largeImageFileName);
                    imageUploadViewModel.LargeImage.SaveAs(largeImageFilePath);
                }
                else
                {
                    image.LargeImage = null;
                }

                //Storing Extra Image Path
                if (imageUploadViewModel.ExtraImage != null)
                {
                    string extraImageFileName = Guid.NewGuid().ToString() + Path.GetFileName(imageUploadViewModel.ExtraImage.FileName);
                    string extraImageFilePath = Path.Combine(Server.MapPath(applicationPath), extraImageFileName);
                    image.ExtraImage0 = string.Format(@"http://localhost:49217/Content/images/cart-image-icons/{0}", extraImageFileName);
                    imageUploadViewModel.ExtraImage.SaveAs(extraImageFilePath);
                }
                else
                {
                    image.ExtraImage0 = null;
                }

                //Storing Extra Image1 Path
                if (imageUploadViewModel.ExtraImage1 != null)
                {
                    string extraImage1FileName = Guid.NewGuid().ToString() + Path.GetFileName(imageUploadViewModel.ExtraImage1.FileName);
                    string extraImage1FilePath = Path.Combine(Server.MapPath(applicationPath), extraImage1FileName);
                    image.ExtraImage1 = string.Format(@"http://localhost:49217/Content/images/cart-image-icons/{0}", extraImage1FileName);
                    imageUploadViewModel.ExtraImage1.SaveAs(extraImage1FilePath);
                }
                else 
                {
                    image.ExtraImage1 = null;
                }


                //Storing Extra Image2 Path
                if (imageUploadViewModel.ExtraImage2 != null)
                {
                    string extraImage2FileName = Guid.NewGuid().ToString() + Path.GetFileName(imageUploadViewModel.ExtraImage2.FileName);
                    string extraImage2FilePath = Path.Combine(Server.MapPath(applicationPath), extraImage2FileName);
                    image.ExtraImage2 = string.Format(@"http://localhost:49217/Content/images/cart-image-icons/{0}", extraImage2FileName);
                    imageUploadViewModel.ExtraImage2.SaveAs(extraImage2FilePath);
                }
                else
                {
                    image.ExtraImage2 = null;
                }
                image.ProductID = imageUploadViewModel.ProductID;

                repository.SaveImage(image);
                TempData["Message"] = "Image successfully saved ";
                return RedirectToAction("Index");
            }
            else
            {
                return View(imageUploadViewModel);
            }
        }

    }
}

SportsStore.WebUI.Admin/Views/ProductAdmin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h2 style="color:#00B4E1">Edit @Model.Name</h2>
    </div>


    @using (Html.BeginForm("Edit", "ProductAdmin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="panel-body">

            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.ProductID)

            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsDiscontinued, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                            @Html.EditorFor(model => model.IsDiscontinued)
                            @Html.ValidationMessageFor(model => model.IsDiscontinued, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InStock, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                            @Html.EditorFor(model => model.InStock)
                            @Html.ValidationMessageFor(model => model.InStock, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UnitCost, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UnitCost, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UnitCost, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AltPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AltPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AltPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Footer, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Footer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Footer, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsTaxed, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IsTaxed)
                        @Html.ValidationMessageFor(model => model.IsTaxed, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaximumProductQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MaximumProductQuantity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaximumProductQuantity, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductOrder, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductOrder, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Group, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Group, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Group, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

SportsStore.WebUI.Admin/Views/ProductAdmin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Products</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th>Short Description</th>
                <th class="text-right">Alternative Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right col-md-1">@item.ProductID</td>
                    <td class="col-md-2">
                        @Html.ActionLink((string)item.Name, "Edit", new
                           {
                               item.ProductID
                           })
                    </td>
                    <td class="col-md-5">
                        @item.ShortDescription
                    </td>
                    <td class="text-right col-md-1">@item.AltPrice.ToString("c")</td>
                    <td class="col-md-3">                        
                        @Html.ActionLink("Delete", "Delete", new { controller = "ProductAdmin", ProductID = item.ProductID }) |
                        @Html.ActionLink("Edit Product Spec", "Edit", new { controller = "ProductSpecification", ProductID = item.ProductID }) |
                        @Html.ActionLink("Edit Image", "UploadImage", new { controller = "ProductAdmin", ProductID = item.ProductID }) |
                        @Html.ActionLink("Product Feature", "EditProductFeature", new { controller = "ProductSpecification",ProductID = item.ProductID }) |
                        @Html.ActionLink("Product Category", "Edit", new { controller = "ProductCategoryAdmin", ProductID = item.ProductID })
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a new product", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>

SportsStore.WebUI.Admin/Views/ProductAdmin/UploadImage.cshtml
@model SportsStore.WebUI.Admin.Models.ImageUploadViewModel

@{
    ViewBag.Title = "Upload Image Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 style="color:#00B4E1">Upload image for @ViewBag.ProductName</h2>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("UploadImage", "ProductAdmin", FormMethod.Post, new { enctype="multipart/form-data"}))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*<div class="form-group">
                    @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("Product", ViewBag.ProductName, new { @class = "form-control col-md-5", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                @Html.Hidden("ProductID",Model.ProductID)
                <div class="form-group">
                    @Html.LabelFor(model => model.ImageDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ImageDescription, new { htmlAttributes = new { @class = "form-control col-md-6" } })
                        @Html.ValidationMessageFor(model => model.ImageDescription, "", new { @class = "text-danger" })
                    </div>
                </div>


                @* Div Control for small image *@
                <div class="form-group">
                    @Html.LabelFor(x => x.SmallImage, new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(x => x.SmallImage, new { type = "file", @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(x => x.SmallImage)
                    </div>
                    <div class="col-md-5">
                        <button type="submit" class="btn-sm btn-primary">Upload</button>
                    </div>
                </div>



                @* Div Control for small image *@
                <div class="form-group">
                    @Html.LabelFor(x => x.MediumImage, new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(x => x.MediumImage, new { type = "file", @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(x => x.MediumImage)
                    </div>
                    <div class="col-md-5">
                        <button type="submit" class="btn-sm btn-primary">Upload</button>
                    </div>
                </div>


                @* Div Control for small image *@
                <div class="form-group">
                    @Html.LabelFor(x => x.LargeImage, new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(x => x.LargeImage, new { type = "file", @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(x => x.LargeImage)
                    </div>
                    <div class="col-md-5">
                        <button type="submit" class="btn-sm btn-primary">Upload</button>
                    </div>
                </div>


                @* Div Control for small image *@
                <div class="form-group">
                    @Html.LabelFor(x => x.ExtraImage, new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(x => x.ExtraImage, new { type = "file", @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(x => x.ExtraImage)
                    </div>
                    <div class="col-md-5">
                        <button type="submit" class="btn-sm btn-primary">Upload</button>
                    </div>
                </div>


                @* Div Control for small image *@
                <div class="form-group">
                    @Html.LabelFor(x => x.ExtraImage1, new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(x => x.ExtraImage1, new { type = "file", @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(x => x.ExtraImage1)
                    </div>
                    <div class="col-md-5">
                        <button type="submit" class="btn-sm btn-primary">Upload</button>
                    </div>
                </div>


                @* Div Control for Extra 2 image *@
                <div class="form-group">
                    @Html.LabelFor(x => x.ExtraImage2, new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(x => x.ExtraImage2, new { type = "file", @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(x => x.ExtraImage2)
                    </div>
                    <div class="col-md-5">
                        <button type="submit" class="btn-sm btn-primary">Upload</button>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>